name: Example
options:
  postGenCommand: pod install
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
targets:
  ExampleApp:
    type: application
    platform: iOS
    sources:
      - path: Example/
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1,2
        INFOPLIST_FILE: Example/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.cpfandcnpjtools
        PRODUCT_MODULE_NAME: ExampleApp
